{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "paperless.fullname" . }}-gotenberg
  labels:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    helm.sh/chart: {{ include "paperless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: gotenberg
spec:
  strategy:
    {{- toYaml .Values.gotenberg.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: gotenberg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: {{ include "gotenberg.image" . }}
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy | quote }}
          args:
              - gotenberg
              - --chromium-disable-javascript=true
              - --chromium-allow-list=file:///tmp/.*
          ports:
          - name: gotenberg
            containerPort: {{ .Values.gotenberg.containerPort }}
            protocol: TCP
          {{- with .Values.gotenberg.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: gotenberg
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.gotenberg.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: gotenberg
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.gotenberg.startupProbe }}
          {{- if .enabled }}
          startupProbe:
            httpGet:
              path: /health
              port: gotenberg
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.gotenberg.resources | nindent 12 }}
          {{- with .Values.gotenberg.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}