{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "paperless.fullname" . }}-gotenberg
  labels:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    helm.sh/chart: {{ include "paperless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: gotenberg
spec:
  type: {{ .Values.gotenberg.service.type }}
  {{- if and (eq .Values.gotenberg.service.type "LoadBalancer") .Values.gotenberg.service.loadBalancerIP }}
  loadBalancerIP: {{ default "" .Values.gotenberg.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.gotenberg.service.ipFamilies }}
  ipFamilies: 
  {{- toYaml .Values.gotenberg.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- if .Values.gotenberg.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.gotenberg.service.ipFamilyPolicy }}
  {{- end }}
  ports:
  - port: {{ .Values.gotenberg.service.port }}
    targetPort: gotenberg
    protocol: TCP
    name: gotenberg
    {{- if eq .Values.gotenberg.service.type "NodePort" }}
    nodePort: {{ default "" .Values.gotenberg.service.nodePort}}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gotenberg
{{- end }}