{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "paperless.fullname" . }}-tika
  labels:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    helm.sh/chart: {{ include "paperless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: tika
spec:
  strategy:
    {{- toYaml .Values.tika.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: tika
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: tika
    spec:
      containers:
        - name: tika
          image: {{ include "tika.image" . }}
          imagePullPolicy: {{ .Values.tika.image.pullPolicy | quote }}
          ports:
          - name: tika
            containerPort: {{ .Values.tika.containerPort }}
            protocol: TCP
          {{- with .Values.tika.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: tika
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.tika.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: tika
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.tika.startupProbe }}
          {{- if .enabled }}
          startupProbe:
            httpGet:
              path: /
              port: tika
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.tika.resources | nindent 12 }}
          {{- with .Values.tika.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}