{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "paperless.fullname" . }}-tika
  labels:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    helm.sh/chart: {{ include "paperless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: tika
spec:
  type: {{ .Values.tika.service.type }}
  {{- if and (eq .Values.tika.service.type "LoadBalancer") .Values.tika.service.loadBalancerIP }}
  loadBalancerIP: {{ default "" .Values.tika.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.tika.service.ipFamilies }}
  ipFamilies: 
  {{- toYaml .Values.tika.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- if .Values.tika.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.tika.service.ipFamilyPolicy }}
  {{- end }}
  ports:
  - port: {{ .Values.tika.service.port }}
    targetPort: tika
    protocol: TCP
    name: tika
    {{- if eq .Values.tika.service.type "NodePort" }}
    nodePort: {{ default "" .Values.tika.service.nodePort}}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tika
{{- end }}