{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.export.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "paperless.fullname" . }}-export
  labels:
    app.kubernetes.io/name: {{ include "paperless.name" . }}
    helm.sh/chart: {{ include "paperless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: paperless
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.export.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.export.size | quote }}
{{- if .Values.persistence.export.storageClass }}
{{- if (eq "-" .Values.persistence.export.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.export.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}